version: '3.8'

services:
  version: '3'

services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - federation
  user_service:
    container_name: user_service
    restart: always
    build:
      context: ./user-service
    ports:
      - "4001:4001"
    expose:
      - "4001"
    networks:
      - federation
    volumes:
      - ./user-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis
    env_file:
      - ./user-service/.env
    command: npm run start
  posts_service:
    container_name: posts_service
    restart: always
    build:
      context: ./posts-service
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - federation
    volumes:
      - ./posts-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis
    links:
      - redis:redis
    env_file:
      - ./posts-service/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379   
    command: npm run start
  gateway_service:
    container_name: gateway_service
    restart: always
    build:
      context: ./gateway-service
    ports:
      - 4002:4002
    networks:
      - federation
    volumes:
      - ./gateway-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - posts_service
      - user_service
    env_file:
      - ./gateway-service/.env
    environment:
      - USERS_SERVICE_URL=http://user_service:4001/graphql
      - POSTS_SERVICE_URL=http://posts_service:4000/graphql
    command: npm start
  subscription_service:
    container_name: subscription_service
    restart: always
    build:
      context: ./subscription-service
    ports:
      - 5000:5000
    networks:
      - federation
    volumes:
      - ./subscription-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis
      - gateway_service
    env_file:
      - ./subscription-service/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
      - GATEWAY_API_URL=http://gateway_service:4002/api
    command: npm start
  react_app:
    container_name: react_app
    restart: always
    build:
      context: ./react-app
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - gateway_service
      - subscription_service
    env_file:
      - ./react-app/.env
    environment:
      - REACT_APP_GATEWAY_API_URL=http://gateway_service:4002
    #   - REACT_APP_SUBSCRIPTIONS_API_URL=ws://subscription_service:5000/graphql
    ports:
      - 3000:3000
    networks:
      - federation
    stdin_open: true
    command: npm start
networks:
  federation:
    name: federation
    driver: bridge
