version: '3.8'

services:
  gateway:
    container_name: gateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    volumes:
      - .:/app
      - /app/node_modules # Anonymous volume for node_modules, prevents it from being blown out during build -> run
      - ./migrations:/app/migrations
    command: npm run start:dev
    # volumes:
    #   - ../example/subscriptions-server:/home/node/app
    #   - ../:/home/node/federation-subscription-tools
    #   - /home/node/app/node_modules
    #   - /home/node/federation-subscription-tools/node_modules
    # depends_on:
    #   - gateway_server
    #   - redis
    # env_file:
    #   - ./subscriptions-server/.env
    # command: npm run server
  # react_app:
  #   container_name: react_app
  #   restart: always
  #   build:
  #     context: ./react-app
  #   volumes:
  #     - ./react-app:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - ./react-app/.env
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   command: npm start
